[package]
name = "vulkano_book"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = "1.23.0"
vulkano = "0.35.1"
vulkano-shaders = "0.35.0"
image = "0.25.6"
winit = "0.30.10"

[profile.dev]
opt-level = 1 
